/**
 * Centralized realistic mock dataset for GigFinance Part 2
 * Tailored for Indian gig workers across Swiggy, Zomato, Uber, Ola, Porter
 */

export const MOCK_TRANSACTIONS = [
  {
    id: 'tx_01',
    date: '2026-09-03',
    description: 'SWIGGY PAYOUT',
    category: 'Gig Income',
    type: 'credit',
    amount: 1250,
    platform: 'Swiggy',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_02',
    date: '2026-09-03',
    description: 'HPCL PETROL',
    category: 'Fuel',
    type: 'debit',
    amount: 400,
    platform: 'HPCL Fuel Station',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_03',
    date: '2026-09-02',
    description: 'ZOMATO PAYOUT',
    category: 'Gig Income',
    type: 'credit',
    amount: 980,
    platform: 'Zomato',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_04',
    date: '2026-09-01',
    description: 'RENT PAYMENT',
    category: 'Housing',
    type: 'debit',
    amount: 5000,
    platform: 'UPI Transfer',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_05',
    date: '2026-09-01',
    description: 'SWIGGY WEEKEND SURGE INCENTIVE',
    category: 'Gig Income',
    type: 'credit',
    amount: 850,
    platform: 'Swiggy',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_06',
    date: '2026-08-31',
    description: 'INDIANOIL FUEL STOP',
    category: 'Fuel',
    type: 'debit',
    amount: 350,
    platform: 'IOCL Pump',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_07',
    date: '2026-08-30',
    description: 'UBER TRIPS SETTLEMENT',
    category: 'Gig Income',
    type: 'credit',
    amount: 1650,
    platform: 'Uber',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_08',
    date: '2026-08-30',
    description: 'CHAAYOS & TIFFIN',
    category: 'Food',
    type: 'debit',
    amount: 140,
    platform: 'UPI Payment',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_09',
    date: '2026-08-29',
    description: 'MOBILE RECHARGE (JIO 84 DAYS)',
    category: 'Bills',
    type: 'debit',
    amount: 666,
    platform: 'Jio Prepaid',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_10',
    date: '2026-08-28',
    description: 'ZOMATO PEAK HOURS PAYOUT',
    category: 'Gig Income',
    type: 'credit',
    amount: 1420,
    platform: 'Zomato',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_11',
    date: '2026-08-27',
    description: 'MOTORCYCLE ENGINE OIL SERVICE',
    category: 'Other',
    type: 'debit',
    amount: 650,
    platform: 'Castrol Auto Garage',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_12',
    date: '2026-08-26',
    description: 'PORTER CITY DELIVERY EARNING',
    category: 'Gig Income',
    type: 'credit',
    amount: 780,
    platform: 'Porter',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_13',
    date: '2026-08-25',
    description: 'GROCERIES D-MART READY',
    category: 'Food',
    type: 'debit',
    amount: 1850,
    platform: 'DMart UPI',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_14',
    date: '2026-08-24',
    description: 'SWIGGY DINNER PEAK PAYOUT',
    category: 'Gig Income',
    type: 'credit',
    amount: 1100,
    platform: 'Swiggy',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_15',
    date: '2026-08-23',
    description: 'BHARAT PETROLEUM FUEL',
    category: 'Fuel',
    type: 'debit',
    amount: 420,
    platform: 'BPCL Petrol',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_16',
    date: '2026-08-22',
    description: 'ELECTRICITY BILL (BESCOM)',
    category: 'Bills',
    type: 'debit',
    amount: 890,
    platform: 'BillDesk UPI',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_17',
    date: '2026-08-21',
    description: 'SWIGGY DAILY PAYOUT',
    category: 'Gig Income',
    type: 'credit',
    amount: 1350,
    platform: 'Swiggy',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_18',
    date: '2026-08-20',
    description: 'FRIEND UPI REPAYMENT',
    category: 'Other Income',
    type: 'credit',
    amount: 500,
    platform: 'UPI Transfer',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_19',
    date: '2026-08-19',
    description: 'HPCL PETROL REFILL',
    category: 'Fuel',
    type: 'debit',
    amount: 380,
    platform: 'HPCL Pump',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_20',
    date: '2026-08-18',
    description: 'ZOMATO FESTIVAL RAIN BONUS',
    category: 'Gig Income',
    type: 'credit',
    amount: 1850,
    platform: 'Zomato',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_21',
    date: '2026-08-17',
    description: 'VEHICLE INSURANCE EMI',
    category: 'Bills',
    type: 'debit',
    amount: 1200,
    platform: 'AutoDebit',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
  {
    id: 'tx_22',
    date: '2026-08-16',
    description: 'SWIGGY WEEKLY SETTLEMENT',
    category: 'Gig Income',
    type: 'credit',
    amount: 2450,
    platform: 'Swiggy',
    status: 'Completed',
    accountMask: 'XXXX XXXX 4521',
  },
];

export const MOCK_DASHBOARD_STATS = {
  monthlyIncome: 24850,
  monthlyExpenses: 15420,
  totalSavings: 4200,
  gigScore: 742,
  gigScoreMax: 900,
  gigScoreTier: 'GOOD',
};

export const MOCK_SAFE_TO_SPEND = {
  amount: 620,
  label: 'Safe to Spend Today',
  subtitle: 'Recommended spending limit for today',
  totalBuffer: 1850,
  committedDailyNeeds: 450,
  recommendedBufferPercent: 68,
  breakdown: [
    { label: 'Available Cashflow Today', amount: 1250 },
    { label: 'Committed Vehicle Fuel & Food', amount: -430 },
    { label: 'Daily Rent & Bill Accrual', amount: -200 },
    { label: 'Recommended Smart Savings', amount: -62 },
    { label: 'Calculated Safe to Spend', amount: 620, isFinal: true },
  ],
};

export const MOCK_SAVINGS_GOALS = [
  {
    id: 'goal_1',
    name: 'Bike Repair Fund',
    currentAmount: 2500,
    targetAmount: 5000,
    category: 'Emergency / Vehicle',
    iconName: 'Wrench',
    targetDate: '2026-10-15',
    color: '#3b82f6',
  },
  {
    id: 'goal_2',
    name: 'Emergency Fund',
    currentAmount: 1700,
    targetAmount: 10000,
    category: 'Resilience',
    iconName: 'ShieldAlert',
    targetDate: '2026-12-31',
    color: '#10b981',
  },
  {
    id: 'goal_3',
    name: 'New Scooter',
    currentAmount: 8000,
    targetAmount: 50000,
    category: 'Asset Building',
    iconName: 'Bike',
    targetDate: '2027-06-30',
    color: '#8b5cf6',
  },
];

export const MOCK_SMART_SAVINGS_RULE = {
  todayEarnings: 1250,
  recommendedAmount: 62,
  ruleDescription: 'Based on your savings rule (5% of daily payouts above ₹500), we recommend saving ₹62.',
  targetGoalId: 'goal_1',
  targetGoalName: 'Bike Repair Fund',
};

export const MOCK_FINANCIAL_GUIDANCE = [
  {
    id: 'guide_1',
    type: 'positive',
    badge: 'Earnings Spike',
    title: 'Your earnings increased 20% this week',
    description: 'Festival demand across Swiggy and Zomato yielded ₹4,250 over the weekend. Great consistency!',
    actionText: 'Allocate Surplus',
    actionRoute: '/savings',
  },
  {
    id: 'guide_2',
    type: 'actionable',
    badge: 'Smart Allocation',
    title: 'Consider moving ₹200 toward your Bike Repair Fund',
    description: 'Locking away ₹200 today protects your safe-to-save buffer against mid-week fuel surges.',
    actionText: 'Save ₹200',
    actionRoute: '/savings',
  },
  {
    id: 'guide_3',
    type: 'caution',
    badge: 'Upcoming Commitment',
    title: 'Rent payment due in 5 days',
    description: '₹5,000 monthly room rent payment due on 1st. Current buffer is on track to cover 100% with zero borrowing.',
    actionText: 'View Cash Flow',
    actionRoute: '/analytics',
  },
];

export const MOCK_ANALYTICS_DATA = {
  stats: {
    monthlyIncome: 24850,
    averageDailyIncome: 828,
    incomeConsistency: 82,
    highestEarningDay: 1850,
  },
  insight: 'Your income is irregular, but your payout pattern shows consistent earning activity.',
  incomeSplit: {
    gigIncome: 23600,
    otherIncome: 1250,
    gigPercent: 95,
    otherPercent: 5,
  },
  expenseCategories: [
    { name: 'Housing', amount: 5000, percent: 32.4, color: '#3b82f6' },
    { name: 'Food', amount: 3840, percent: 24.9, color: '#10b981' },
    { name: 'Fuel', amount: 3250, percent: 21.1, color: '#f59e0b' },
    { name: 'Bills', amount: 2150, percent: 13.9, color: '#8b5cf6' },
    { name: 'Other', amount: 1180, percent: 7.7, color: '#64748b' },
  ],
  chartData: {
    daily: [
      { label: 'Mon', income: 980, expense: 540 },
      { label: 'Tue', income: 1150, expense: 620 },
      { label: 'Wed', income: 780, expense: 410 },
      { label: 'Thu', income: 1420, expense: 780 },
      { label: 'Fri', income: 1350, expense: 890 },
      { label: 'Sat', income: 1850, expense: 920 },
      { label: 'Sun', income: 1650, expense: 750 },
    ],
    weekly: [
      { label: 'Week 1', income: 5800, expense: 3900 },
      { label: 'Week 2', income: 6450, expense: 4100 },
      { label: 'Week 3', income: 5200, expense: 3200 },
      { label: 'Week 4', income: 7400, expense: 4220 },
    ],
    monthly: [
      { label: 'May', income: 21200, expense: 14200 },
      { label: 'Jun', income: 22800, expense: 14900 },
      { label: 'Jul', income: 23400, expense: 15100 },
      { label: 'Aug', income: 24850, expense: 15420 },
    ],
  },
};
